#!/bin/sh
#
# This file is part of OpenMediaVault.
#
# @license   http://www.gnu.org/licenses/gpl.html GPL Version 3
# @author    Volker Theile <volker.theile@openmediavault.org>
# @copyright Copyright (c) 2009-2015 Volker Theile
#
# OpenMediaVault is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# any later version.
#
# OpenMediaVault is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with OpenMediaVault. If not, see <http://www.gnu.org/licenses/>.

# Documentation/Howto:
# http://linux.die.net/man/8/cryptsetup
# http://linux.die.net/man/5/crypttab
# https://gitlab.com/cryptsetup/cryptsetup

set -e

. /etc/default/openmediavault
. /usr/share/openmediavault/scripts/helper-functions

OMV_LUKS_CRYPTDISKS_DEFAULT=${OMV_LUKS_CRYPTDISKS_DEFAULT:-"/etc/default/cryptdisks"}
OMV_LUKS_CRYPTTAB_CONFIG=${OMV_LUKS_CRYPTTAB_CONFIG:-"/etc/crypttab"}
OMV_LUKS_CRYPTDISKS_INITSCRIPT=${OMV_LUKS_CRYPTDISKS_INITSCRIPT:-"/etc/init.d/cryptdisks"}
OMV_LUKS_CRYPTDISKS_EARLY_INITSCRIPT=${OMV_LUKS_CRYPTDISKS_EARLY_INITSCRIPT:-"/etc/init.d/cryptdisks-early"}
OMV_LUKS_CRYPTDISKS_ENABLE=${OMV_LUKS_CRYPTDISKS_ENABLE:-"Yes"}
OMV_LUKS_CRYPTDISKS_MOUNT=${OMV_LUKS_CRYPTDISKS_MOUNT:-""}

# Generate configuration files
mkconf() {

# Create the '/etc/default/cryptdisks' file.
cat > ${OMV_LUKS_CRYPTDISKS_DEFAULT} <<EOF
# Run cryptdisks initscripts at startup? Default is Yes.
CRYPTDISKS_ENABLE=${OMV_LUKS_CRYPTDISKS_ENABLE}

# Mountpoints to mount, before cryptsetup is invoked at initscripts. Takes
# mountpoins which are configured in /etc/fstab as arguments. Separate
# mountpoints by space.
# This is useful for keyfiles on removable media. Default is unset.
CRYPTDISKS_MOUNT="${OMV_LUKS_CRYPTDISKS_MOUNT}"

# Default check script. Takes effect, if the 'check' option is set in crypttab
# without a value.
CRYPTDISKS_CHECK=blkid

# Default precheck script. Takes effect, if the 'precheck' option is set in
# crypttab without a value.
# Default is 'un_blkid' for plain dm-crypt devices if unset here.
CRYPTDISKS_PRECHECK=
EOF

# Create the '/etc/crypttab' file.
cat > ${OMV_LUKS_CRYPTTAB_CONFIG} <<EOF
# <target name> <source device>         <key file>      <options>
EOF

}


case "$1" in
mkconf|*)
  # Do nothing for the time being...
  # mkconf
  ;;
esac
exit 0
